version: "3.8"

services:
  sql3:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_serv-COVID
    ports:
      - "1433:1433"
    user: root
    volumes:
      - ${DOCKER_VOLUMES_PATH}/sql/data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=${SQL_PASSWORD:-Connect123}
      - MSSQL_PID=${SQL_PID:-Developer}
      - MSSQL_USER=${SQL_USERNAME:-SA}
    restart: unless-stopped

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack-COVID
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongodb-COVID
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${DOCKER_VOLUMES_PATH}/mongoDB/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-Connect123}
      MONGO_INITDB_DATABASE: ${MONGO_INIT_DB:-CovidStatistics}
    networks:
      - mongo-database

  mongo-express:
    image: mongo-express
    container_name: mongo-express-COVID
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORDL:-Connect123}
      ME_CONFIG_MONGODB_SERVER: mongodb-COVID
      ME_CONFIG_MONGODB_USEUNIFIEDTOPOLOGY: "true"
    networks:
      - mongo-database

networks:
  mongo-database:
    driver: bridge
